baseURL = "http://blog.jonstodle.com/"
languageCode = "en-us"
title = "Code & Sundry"
theme = "basically"
rssLimit = 20

[author]
    name = "Jon Grythe Stødle"

[permalinks]
    post = "/:filename/"
