backend:
  name: git-gateway

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/post'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Tags', name: 'tags', widget: 'list', allow_add: false}
      - {label: 'Date', name: 'date', widget: 'DateTime'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
